---
# tasks file for roles/learnansible-example-role

- name: "Update all packages to the latest version"
  ansible.builtin.apt:
    name: "*"
    state: "latest"
    update_cache: true
  tags:
    - "skip_ansible_lint"

- name: "Install packages"
  ansible.builtin.apt:
    state: "present"
    pkg:
      - "ntp"
      - "sntp"
      - "ntp-doc"
  tags:
    - "ntp_install"

- name: "Configure NTP"
  ansible.builtin.template:
    src: "./ntp.conf.j2"
    dest: "/etc/ntp.conf"
    mode: "0644"
  tags: 
    - "ntpconf"

- name: "Set timezone to Europe/Paris"
  become: true
  ansible.builtin.timezone:
    name: "Europe/Paris"
  tags:
    - "timezone"

  notify: "Restart ntp"

# - name: Set timezone to Asia/Tokyo
#   become: true
#   community.general.timezone:
#     name: Asia/Tokyo